package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSlideshow<M extends BaseSlideshow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPhotos(java.lang.String photos) {
		set("photos", photos);
	}
	
	public java.lang.String getPhotos() {
		return getStr("photos");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setSign(java.lang.String sign) {
		set("sign", sign);
	}
	
	public java.lang.String getSign() {
		return getStr("sign");
	}

	public void setNid(java.lang.Integer nid) {
		set("nid", nid);
	}
	
	public java.lang.Integer getNid() {
		return getInt("nid");
	}

}
