package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProjectCases<M extends BaseProjectCases<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}
	
	public java.lang.String getPicture() {
		return getStr("picture");
	}

	public void setPictures(java.lang.String pictures) {
		set("pictures", pictures);
	}
	
	public java.lang.String getPictures() {
		return getStr("pictures");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setCasepicture(java.lang.String casepicture) {
		set("casepicture", casepicture);
	}
	
	public java.lang.String getCasepicture() {
		return getStr("casepicture");
	}

}
