package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicUser<M extends BaseDicUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}
	
	public java.lang.String getId() {
		return getStr("ID");
	}

	public void setUserCode(java.lang.String userCode) {
		set("USER_CODE", userCode);
	}
	
	public java.lang.String getUserCode() {
		return getStr("USER_CODE");
	}

	public void setUserName(java.lang.String userName) {
		set("USER_NAME", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("USER_NAME");
	}

	public void setPasswd(java.lang.String passwd) {
		set("PASSWD", passwd);
	}
	
	public java.lang.String getPasswd() {
		return getStr("PASSWD");
	}

	public void setUnitId(java.lang.String unitId) {
		set("UNIT_ID", unitId);
	}
	
	public java.lang.String getUnitId() {
		return getStr("UNIT_ID");
	}

	public void setSalt(java.lang.String salt) {
		set("SALT", salt);
	}
	
	public java.lang.String getSalt() {
		return getStr("SALT");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("CREATER_ID", createrId);
	}
	
	public java.lang.String getCreaterId() {
		return getStr("CREATER_ID");
	}

	public void setParentId(java.lang.String parentId) {
		set("PARENT_ID", parentId);
	}
	
	public java.lang.String getParentId() {
		return getStr("PARENT_ID");
	}

	public void setType(java.math.BigDecimal type) {
		set("TYPE", type);
	}
	
	public java.math.BigDecimal getType() {
		return get("TYPE");
	}

	public void setIsDisabled(java.math.BigDecimal isDisabled) {
		set("IS_DISABLED", isDisabled);
	}
	
	public java.math.BigDecimal getIsDisabled() {
		return get("IS_DISABLED");
	}

	public void setEntryTime(java.util.Date entryTime) {
		set("ENTRY_TIME", entryTime);
	}
	
	public java.util.Date getEntryTime() {
		return get("ENTRY_TIME");
	}

}
