package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePartnersIndex<M extends BasePartnersIndex<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCover(java.lang.String cover) {
		set("cover", cover);
	}
	
	public java.lang.String getCover() {
		return getStr("cover");
	}

	public void setPartnersid(java.lang.Integer partnersid) {
		set("partnersid", partnersid);
	}
	
	public java.lang.Integer getPartnersid() {
		return getInt("partnersid");
	}

}
