package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNewsindex<M extends BaseNewsindex<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPictures(java.lang.String pictures) {
		set("pictures", pictures);
	}
	
	public java.lang.String getPictures() {
		return getStr("pictures");
	}

	public void setNewsid(java.lang.Integer newsid) {
		set("newsid", newsid);
	}
	
	public java.lang.Integer getNewsid() {
		return getInt("newsid");
	}

}
