package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSucceed<M extends BaseSucceed<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCommodityName(java.lang.String commodityName) {
		set("commodity_name", commodityName);
	}
	
	public java.lang.String getCommodityName() {
		return getStr("commodity_name");
	}

	public void setGet(java.lang.Integer get) {
		set("get", get);
	}
	
	public java.lang.Integer getGet() {
		return getInt("get");
	}

	public void setGetPeopel(java.lang.String getPeopel) {
		set("get_peopel", getPeopel);
	}
	
	public java.lang.String getGetPeopel() {
		return getStr("get_peopel");
	}

	public void setGetTime(java.util.Date getTime) {
		set("get_time", getTime);
	}
	
	public java.util.Date getGetTime() {
		return get("get_time");
	}

	public void setResidue(java.lang.Integer residue) {
		set("residue", residue);
	}
	
	public java.lang.Integer getResidue() {
		return getInt("residue");
	}

}
