package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEmployment<M extends BaseEmployment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSkill(java.lang.String skill) {
		set("skill", skill);
	}
	
	public java.lang.String getSkill() {
		return getStr("skill");
	}

	public void setReleasedate(java.util.Date releasedate) {
		set("releasedate", releasedate);
	}
	
	public java.util.Date getReleasedate() {
		return get("releasedate");
	}

	public void setPnumber(java.lang.String pnumber) {
		set("pnumber", pnumber);
	}
	
	public java.lang.String getPnumber() {
		return getStr("pnumber");
	}

	public void setIconid(java.lang.Integer iconid) {
		set("iconid", iconid);
	}
	
	public java.lang.Integer getIconid() {
		return getInt("iconid");
	}

}
