package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setOutline(java.lang.String outline) {
		set("outline", outline);
	}
	
	public java.lang.String getOutline() {
		return getStr("outline");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setNewcover(java.lang.String newcover) {
		set("newcover", newcover);
	}
	
	public java.lang.String getNewcover() {
		return getStr("newcover");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setTrenchs(java.lang.String trenchs) {
		set("trenchs", trenchs);
	}
	
	public java.lang.String getTrenchs() {
		return getStr("trenchs");
	}

	public void setOverhead(java.lang.Integer overhead) {
		set("overhead", overhead);
	}
	
	public java.lang.Integer getOverhead() {
		return getInt("overhead");
	}

	public void setNkid(java.lang.Integer nkid) {
		set("nkid", nkid);
	}
	
	public java.lang.Integer getNkid() {
		return getInt("nkid");
	}

}
