package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActivity<M extends BaseActivity<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setActitle(java.lang.String actitle) {
		set("actitle", actitle);
	}
	
	public java.lang.String getActitle() {
		return getStr("actitle");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setActcover(java.lang.String actcover) {
		set("actcover", actcover);
	}
	
	public java.lang.String getActcover() {
		return getStr("actcover");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public void setTrenchs(java.lang.String trenchs) {
		set("trenchs", trenchs);
	}
	
	public java.lang.String getTrenchs() {
		return getStr("trenchs");
	}

	public void setAkid(java.lang.Integer akid) {
		set("akid", akid);
	}
	
	public java.lang.Integer getAkid() {
		return getInt("akid");
	}

}
