package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShangping<M extends BaseShangping<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setSname(java.lang.String sname) {
		set("sname", sname);
	}
	
	public java.lang.String getSname() {
		return getStr("sname");
	}

	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}
	
	public java.lang.String getUname() {
		return getStr("uname");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	public void setBeizhu(java.lang.String beizhu) {
		set("beizhu", beizhu);
	}
	
	public java.lang.String getBeizhu() {
		return getStr("beizhu");
	}

	public void setZhuangtai(java.lang.Integer zhuangtai) {
		set("zhuangtai", zhuangtai);
	}
	
	public java.lang.Integer getZhuangtai() {
		return getInt("zhuangtai");
	}

}
