package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBusinessById<M extends BaseBusinessById<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}
	
	public java.lang.String getPicture() {
		return getStr("picture");
	}

	public void setBusinessid(java.lang.Integer businessid) {
		set("businessId", businessid);
	}
	
	public java.lang.Integer getBusinessid() {
		return getInt("businessId");
	}

	public void setBuidName(java.lang.String buidName) {
		set("buid_name", buidName);
	}
	
	public java.lang.String getBuidName() {
		return getStr("buid_name");
	}

	public void setByidTitle(java.lang.String byidTitle) {
		set("byid_title", byidTitle);
	}
	
	public java.lang.String getByidTitle() {
		return getStr("byid_title");
	}

	public void setByidTitles(java.lang.String byidTitles) {
		set("byid_titles", byidTitles);
	}
	
	public java.lang.String getByidTitles() {
		return getStr("byid_titles");
	}

}
