package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicRole<M extends BaseDicRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}
	
	public java.lang.String getId() {
		return getStr("ID");
	}

	public void setRoleName(java.lang.String roleName) {
		set("ROLE_NAME", roleName);
	}
	
	public java.lang.String getRoleName() {
		return getStr("ROLE_NAME");
	}

	public void setXh(java.math.BigDecimal xh) {
		set("XH", xh);
	}
	
	public java.math.BigDecimal getXh() {
		return get("XH");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

	public void setParentId(java.lang.String parentId) {
		set("PARENT_ID", parentId);
	}
	
	public java.lang.String getParentId() {
		return getStr("PARENT_ID");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("CREATER_ID", createrId);
	}
	
	public java.lang.String getCreaterId() {
		return getStr("CREATER_ID");
	}

	public void setType(java.math.BigDecimal type) {
		set("TYPE", type);
	}
	
	public java.math.BigDecimal getType() {
		return get("TYPE");
	}

	public void setIsPrivate(java.math.BigDecimal isPrivate) {
		set("IS_PRIVATE", isPrivate);
	}
	
	public java.math.BigDecimal getIsPrivate() {
		return get("IS_PRIVATE");
	}

	public void setEntryTime(java.util.Date entryTime) {
		set("ENTRY_TIME", entryTime);
	}
	
	public java.util.Date getEntryTime() {
		return get("ENTRY_TIME");
	}

}
