package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMerchandiseType<M extends BaseMerchandiseType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMerchandise(java.lang.String merchandise) {
		set("merchandise", merchandise);
	}
	
	public java.lang.String getMerchandise() {
		return getStr("merchandise");
	}

}
