package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicPopedom<M extends BaseDicPopedom<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}
	
	public java.lang.String getId() {
		return getStr("ID");
	}

	public void setPopedomName(java.lang.String popedomName) {
		set("POPEDOM_NAME", popedomName);
	}
	
	public java.lang.String getPopedomName() {
		return getStr("POPEDOM_NAME");
	}

	public void setForwardAction(java.lang.String forwardAction) {
		set("FORWARD_ACTION", forwardAction);
	}
	
	public java.lang.String getForwardAction() {
		return getStr("FORWARD_ACTION");
	}

	public void setXh(java.math.BigDecimal xh) {
		set("XH", xh);
	}
	
	public java.math.BigDecimal getXh() {
		return get("XH");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

	public void setParentId(java.lang.String parentId) {
		set("PARENT_ID", parentId);
	}
	
	public java.lang.String getParentId() {
		return getStr("PARENT_ID");
	}

	public void setRedirect(java.lang.String redirect) {
		set("REDIRECT", redirect);
	}
	
	public java.lang.String getRedirect() {
		return getStr("REDIRECT");
	}

	public void setNavIcon(java.lang.String navIcon) {
		set("NAV_ICON", navIcon);
	}
	
	public java.lang.String getNavIcon() {
		return getStr("NAV_ICON");
	}

	public void setType(java.math.BigDecimal type) {
		set("TYPE", type);
	}
	
	public java.math.BigDecimal getType() {
		return get("TYPE");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("CREATER_ID", createrId);
	}
	
	public java.lang.String getCreaterId() {
		return getStr("CREATER_ID");
	}

	public void setEntryTime(java.util.Date entryTime) {
		set("ENTRY_TIME", entryTime);
	}
	
	public java.util.Date getEntryTime() {
		return get("ENTRY_TIME");
	}

	public void setIsLog(java.math.BigDecimal isLog) {
		set("IS_LOG", isLog);
	}
	
	public java.math.BigDecimal getIsLog() {
		return get("IS_LOG");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}
	
	public java.lang.String getName() {
		return getStr("NAME");
	}

	public void setComponent(java.lang.String component) {
		set("COMPONENT", component);
	}
	
	public java.lang.String getComponent() {
		return getStr("COMPONENT");
	}

	public void setHref(java.lang.String href) {
		set("HREF", href);
	}
	
	public java.lang.String getHref() {
		return getStr("HREF");
	}

	public void setIsHide(java.math.BigDecimal isHide) {
		set("IS_HIDE", isHide);
	}
	
	public java.math.BigDecimal getIsHide() {
		return get("IS_HIDE");
	}

	public void setIsNotCache(java.math.BigDecimal isNotCache) {
		set("IS_NOT_CACHE", isNotCache);
	}
	
	public java.math.BigDecimal getIsNotCache() {
		return get("IS_NOT_CACHE");
	}

}
