package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRelated<M extends BaseRelated<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setCover(java.lang.String cover) {
		set("cover", cover);
	}
	
	public java.lang.String getCover() {
		return getStr("cover");
	}

	public void setSynopsis(java.lang.String synopsis) {
		set("synopsis", synopsis);
	}
	
	public java.lang.String getSynopsis() {
		return getStr("synopsis");
	}

	public void setLinks(java.lang.String links) {
		set("links", links);
	}
	
	public java.lang.String getLinks() {
		return getStr("links");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("createdate", createdate);
	}
	
	public java.util.Date getCreatedate() {
		return get("createdate");
	}

}
