package com.sojpt.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDisOrder<M extends BaseDisOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setCard(java.lang.String card) {
		set("card", card);
	}
	
	public java.lang.String getCard() {
		return getStr("card");
	}

	public void setMonthdate(java.util.Date monthdate) {
		set("monthDate", monthdate);
	}
	
	public java.util.Date getMonthdate() {
		return get("monthDate");
	}

	public void setMoney(java.lang.String money) {
		set("money", money);
	}
	
	public java.lang.String getMoney() {
		return getStr("money");
	}

}
