package com.sojpt.model;

import com.sojpt.model.base.BaseActkinds;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Actkinds extends BaseActkinds<Actkinds> {
	public static final Actkinds dao = new Actkinds().dao();
}
