package com.sojpt.model;

import com.sojpt.model.base.BaseBigData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BigData extends BaseBigData<BigData> {
	public static final BigData dao = new BigData().dao();
}
