package com.sojpt.model;

import com.sojpt.model.base.BaseBusiness;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Business extends BaseBusiness<Business> {
	public static final Business dao = new Business().dao();
}
