package com.sojpt.model;

import com.sojpt.model.base.BaseBusinessById;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessById extends BaseBusinessById<BusinessById> {
	public static final BusinessById dao = new BusinessById().dao();
}
