package com.sojpt.model;

import com.sojpt.model.base.BaseDicLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicLog extends BaseDicLog<DicLog> {
	public static final DicLog dao = new DicLog().dao();
}
