package com.sojpt.model;

import com.sojpt.model.base.BaseDicPopedom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicPopedom extends BaseDicPopedom<DicPopedom> {
	public static final DicPopedom dao = new DicPopedom().dao();
}
