package com.sojpt.model;

import com.sojpt.model.base.BaseDicRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicRole extends BaseDicRole<DicRole> {
	public static final DicRole dao = new DicRole().dao();
}
