package com.sojpt.model;

import com.sojpt.model.base.BaseDicStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicStudent extends BaseDicStudent<DicStudent> {
	public static final DicStudent dao = new DicStudent().dao();
}
