package com.sojpt.model;

import com.sojpt.model.base.BaseDicUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicUserRole extends BaseDicUserRole<DicUserRole> {
	public static final DicUserRole dao = new DicUserRole().dao();
}
