package com.sojpt.model;

import com.sojpt.model.base.BaseDicUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicUser extends BaseDicUser<DicUser> {
	public static final DicUser dao = new DicUser().dao();
}
