package com.sojpt.model;

import com.sojpt.model.base.BaseDisOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DisOrder extends BaseDisOrder<DisOrder> {
	public static final DisOrder dao = new DisOrder().dao();
}
