package com.sojpt.model;

import com.sojpt.model.base.BaseEmployment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Employment extends BaseEmployment<Employment> {
	public static final Employment dao = new Employment().dao();
}
