package com.sojpt.model;

import com.sojpt.model.base.BaseEnvironmentProtection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EnvironmentProtection extends BaseEnvironmentProtection<EnvironmentProtection> {
	public static final EnvironmentProtection dao = new EnvironmentProtection().dao();
}
