package com.sojpt.model;

import com.sojpt.model.base.BaseIcons;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Icons extends BaseIcons<Icons> {
	public static final Icons dao = new Icons().dao();
}
