package com.sojpt.model;

import com.sojpt.model.base.BaseIndexnews;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Indexnews extends BaseIndexnews<Indexnews> {
	public static final Indexnews dao = new Indexnews().dao();
}
