package com.sojpt.model;

import com.sojpt.model.base.BaseIndexpartner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Indexpartner extends BaseIndexpartner<Indexpartner> {
	public static final Indexpartner dao = new Indexpartner().dao();
}
