package com.sojpt.model;

import com.sojpt.model.base.BaseIntellectualization;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Intellectualization extends BaseIntellectualization<Intellectualization> {
	public static final Intellectualization dao = new Intellectualization().dao();
}
