package com.sojpt.model;

import com.sojpt.model.base.BaseIntellectCase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IntellectCase extends BaseIntellectCase<IntellectCase> {
	public static final IntellectCase dao = new IntellectCase().dao();
}
