package com.sojpt.model;

import com.sojpt.model.base.BaseMerchandiseNew;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchandiseNew extends BaseMerchandiseNew<MerchandiseNew> {
	public static final MerchandiseNew dao = new MerchandiseNew().dao();
}
