package com.sojpt.model;

import com.sojpt.model.base.BaseMerchandiseType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MerchandiseType extends BaseMerchandiseType<MerchandiseType> {
	public static final MerchandiseType dao = new MerchandiseType().dao();
}
