package com.sojpt.model;

import com.sojpt.model.base.BaseNewkinds;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newkinds extends BaseNewkinds<Newkinds> {
	public static final Newkinds dao = new Newkinds().dao();
}
