package com.sojpt.model;

import com.sojpt.model.base.BaseNewsindex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newsindex extends BaseNewsindex<Newsindex> {
	public static final Newsindex dao = new Newsindex().dao();
}
