package com.sojpt.model;

import com.sojpt.model.base.BasePartnerkinds;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Partnerkinds extends BasePartnerkinds<Partnerkinds> {
	public static final Partnerkinds dao = new Partnerkinds().dao();
}
