package com.sojpt.model;

import com.sojpt.model.base.BasePartners;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Partners extends BasePartners<Partners> {
	public static final Partners dao = new Partners().dao();
}
