package com.sojpt.model;

import com.sojpt.model.base.BasePartnersIndex;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PartnersIndex extends BasePartnersIndex<PartnersIndex> {
	public static final PartnersIndex dao = new PartnersIndex().dao();
}
