package com.sojpt.model;

import com.sojpt.model.base.BasePartbanner;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Partbanner extends BasePartbanner<Partbanner> {
	public static final Partbanner dao = new Partbanner().dao();
}
