package com.sojpt.model;

import com.sojpt.model.base.BaseProjectCases;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProjectCases extends BaseProjectCases<ProjectCases> {
	public static final ProjectCases dao = new ProjectCases().dao();
}
