package com.sojpt.model;

import com.sojpt.model.base.BasePromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Promotion extends BasePromotion<Promotion> {
	public static final Promotion dao = new Promotion().dao();
}
