package com.sojpt.model;

import com.sojpt.model.base.BaseQuality;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Quality extends BaseQuality<Quality> {
	public static final Quality dao = new Quality().dao();
}
