package com.sojpt.model;

import com.sojpt.model.base.BaseRelated;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Related extends BaseRelated<Related> {
	public static final Related dao = new Related().dao();
}
