package com.sojpt.model;

import com.sojpt.model.base.BaseRingcase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ringcase extends BaseRingcase<Ringcase> {
	public static final Ringcase dao = new Ringcase().dao();
}
