package com.sojpt.model;

import com.sojpt.model.base.BaseShangping;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shangping extends BaseShangping<Shangping> {
	public static final Shangping dao = new Shangping().dao();
}
