package com.sojpt.model;

import com.sojpt.model.base.BaseSlideshow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Slideshow extends BaseSlideshow<Slideshow> {
	public static final Slideshow dao = new Slideshow().dao();
}
