package com.sojpt.model;

import com.sojpt.model.base.BaseSucceed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Succeed extends BaseSucceed<Succeed> {
	public static final Succeed dao = new Succeed().dao();
}
