package com.sojpt.model;

import com.sojpt.model.base.BaseSupplyChain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplyChain extends BaseSupplyChain<SupplyChain> {
	public static final SupplyChain dao = new SupplyChain().dao();
}
