package com.sojpt.model;

import com.sojpt.model.base.BaseSupplyChainfinance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SupplyChainfinance extends BaseSupplyChainfinance<SupplyChainfinance> {
	public static final SupplyChainfinance dao = new SupplyChainfinance().dao();
}
