package com.sojpt.model;

import com.sojpt.model.base.Base商品;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class 商品 extends Base商品<商品> {
	public static final 商品 dao = new 商品().dao();
}
